### ISSUE TITLE
Search on emtpy input

### ISSUE THREAD

**Issue by ppoetsma** [mendix/InputReferenceSelector#4]
Hi,

The option "Search on empty input" works if you enter data and remove it (backspace). However I would like to get the same result when I click in an empty widget. The list is a hint for the user what the selectable options look like.

Here is the scenario: Open a page/popup with the widget. Use the mouse and click inside the widget to give it the focus. Currently it does not anything. The proposed feature is to show the dropdown/list of the first n (as configured) items.

Regards,
Paul

**Comment by ppoetsma** [comment]
Thanks!

**Comment by JelteMX** [comment]
Will be updated in the AppStore today/tomorrow, it needs to be approved by our tester first
